SwitchZeroBetweenOneの処理の修正
human-osaka-game-2018/GameFramework pull request #106
Opened 2019-03-17 10:22 UTC by Harutaka-Tsujino

## 元Issue

Closes #105

## 変更内容

- [x] 0~1の値になるように修正

## 影響範囲

点滅拡大関数が正常な動作になる

2019-03-17 10:30 UTC, taishi-matsumura commented
「影響範囲」はネガティブなイメージで使うことが多いです。
「ここ変えたらあれとあれにも影響出るから、副作用出てないか確認し直さないといけないね」という意味での「影響範囲」です。

覚えといて〜

2019-03-17 10:33 UTC, taishi-matsumura commented
で、なんで僕がこんなにうるさくレビューしてるかと言うと、ライブラリは影響範囲がめちゃめちゃ広いからです。
ライブラリがバグってるとその被害をほぼ全員が食らいますからね。

2019-03-17 11:04 UTC, taishi-matsumura requested changes

2019-03-17 11:04 UTC, taishi-matsumura commented on GameFramework/Algorithm/Algorithm.h
> +			return fabsf(sin(2.0f * D3DX_PI * progressRatio));
これだと、

|progressRatio|2.0f * D3DX_PI * progressRatio|戻り値|
|---|---|---|
|0.0f|0.0f|0.0f|
|0.25f|1.0f|1.0f|
|0.5f|0.0f|0.0f|
|0.75f|-1.0f|1.0f|
|1.0f|0.0f|0.0f|


になりませんか？

2019-03-17 11:08 UTC, Harutaka-Tsujino commented on GameFramework/Algorithm/Algorithm.h
> +			return fabsf(sin(2.0f * D3DX_PI * progressRatio));
```suggestion
			return sin(D3DX_PI * progressRatio);
```
こうですね

2019-03-17 11:16 UTC, taishi-matsumura requested changes

2019-03-17 11:16 UTC, taishi-matsumura commented on GameFramework/Algorithm/Algorithm.h
> +			return sin(D3DX_PI * progressRatio);
それだと、

|progressRatio|2.0f * D3DX_PI * progressRatio|戻り値|
|---|---|---|
|0.0f|0.0f|0.0f|
|0.25f|1.0f|0.7f|
|0.5f|1.0f|1.0f|
|0.75f|0.7f|0.7f|
|1.0f|0.0f|0.0f|

になりませんか？

0.0f <= progressRatio <= 1.0f なのであれば
```suggestion
			progressRatio /= 2;
			return sin(D3DX_PI * progressRatio);
```
では？

2019-03-17 11:18 UTC, Harutaka-Tsujino commented on GameFramework/Algorithm/Algorithm.h
> +			return sin(D3DX_PI * progressRatio);
仕様として0から1ではなく
０～１～０が一周期としています

2019-03-17 11:24 UTC, taishi-matsumura commented on GameFramework/Algorithm/Algorithm.h
> +			return sin(D3DX_PI * progressRatio);
なるほど。
であれば、これを呼んでいる `SwitchMinBetweenMax()` なりVerticesクラスなりを直さないと一旦maxまで行ってから小さくなってしまいますね。

2019-03-17 11:28 UTC, Harutaka-Tsujino commented on GameFramework/Algorithm/Algorithm.h
> +			return sin(D3DX_PI * progressRatio);
cosからsinに修正したので
1～0～1が0～1～0に戻ったのでminからmaxになっていると思います

2019-03-17 11:57 UTC, taishi-matsumura commented on GameFramework/Algorithm/Algorithm.h
> +			return sin(D3DX_PI * progressRatio);
テスト追加したので動かしてみて下さい

2019-03-17 13:42 UTC, Harutaka-Tsujino commented on GameFramework/Algorithm/Algorithm.h
> +			return sin(D3DX_PI * progressRatio);
ビルドエラーなどで少し手間取っているので学校で教えてもらえるとありがたいです

2019-03-17 13:49 UTC, taishi-matsumura commented on GameFramework/Algorithm/Algorithm.h
> +			return sin(D3DX_PI * progressRatio);
はい、ゲームの方に影響が無いレベルで動いているのなら後回しでも良いかも知れませんね。
こっちのリポジトリは、就活作品としての「まともなライブラリ」を作ろうという取り組みですので。(まぁ、いつかはやらなきゃだけど)

2019-03-17 15:30 UTC, taishi-matsumura commented
@Harutaka-Tsujino 
ソースが先祖返りしていたので再度アップしました。
前にもあったので、気を付けて下さいね。

2019-03-18 05:12 UTC, taishi-matsumura approved these changes
一旦承認しておきますが、矩形を描画する際に「幅や高さの半分」を利用者が意識しなければならないライブラリは見たことがありません。

2019-03-18 05:14 UTC, merged