✨ 当たり判定関数をまとめたものの作成
human-osaka-game-2018/GameFramework pull request #130
Opened 2019-03-21 13:13 UTC by Harutaka-Tsujino

## 元Issue

Closes #129
## 変更内容

- [x] 当たり判定をとるために矩形クラスのアクセサの作成
- [x] 矩形クラスの描画用のサイズを渡すために処理の変更
- [x] 当たり判定名前空間の作成
## 補足

矩形が回転した際の当たり判定も取れるようにしています

2019-03-21 15:17 UTC, taishi-matsumura requested changes
collisionの便利関数群、良いと思います 👍

2019-03-21 15:17 UTC, taishi-matsumura commented on GameFramework/GameFramework/Collision/Collision.cpp
> +				D3DXVECTOR3 vec3Tmp = pVertices[(i + 1) % 4].m_pos - pVertices[i].m_pos;
こんなのこそ演算子オーバーロードがあると良さそうですね。

2019-03-21 15:17 UTC, taishi-matsumura commented on GameFramework/GameFramework/Collision/Collision.cpp
> +			for (int i = 0; i < CustomVertex::RECT_VERTICES_NUM; ++i)
以前から思っていたのですが、もし矩形が前提なのであれば頂点は4つと決まっているはずなのでファーストクラスコレクションにしてしまった方が良さそうです。

2019-03-21 15:17 UTC, taishi-matsumura commented on GameFramework/GameFramework/Collision/Collision.cpp
> +				float degree = algorithm::D3DXVec2CalcDegree(pSideVecs[i], pVecsVToP[i]);
このベクトルの集合体も矩形前提のようなので、ファーストクラスコレクションにすると良いと思います。

2019-03-21 15:17 UTC, taishi-matsumura commented on GameFramework/GameFramework/Vertices/Vertices.h
> +			if (m_hasUpdatedSize) return m_baseSize;
元のサイズから描画用に変更されていたら描画用のサイズを返すのでは？
フラグ逆じゃないですか？

2019-03-21 15:17 UTC, taishi-matsumura commented on GameFramework/GameFramework/Vertices/Vertices.h
> +		virtual void Normalize() = 0;
これは「正規化」かなぁ？ちょっと違和感あります。

2019-03-22 13:38 UTC, Harutaka-Tsujino commented on GameFramework/GameFramework/Vertices/Vertices.h
> +		virtual void Normalize() = 0;
CreateCustomVerticesに変更しました

2019-03-22 13:38 UTC, Harutaka-Tsujino commented on GameFramework/GameFramework/Vertices/Vertices.h
> +			if (m_hasUpdatedSize) return m_baseSize;
逆です修正しました

2019-03-22 13:39 UTC, Harutaka-Tsujino commented on GameFramework/GameFramework/Collision/Collision.cpp
> +			for (int i = 0; i < CustomVertex::RECT_VERTICES_NUM; ++i)
矩形に関連したものをファーストクラスコレクションにしました

2019-03-22 13:39 UTC, Harutaka-Tsujino commented on GameFramework/GameFramework/Collision/Collision.cpp
> +				D3DXVECTOR3 vec3Tmp = pVertices[(i + 1) % 4].m_pos - pVertices[i].m_pos;
ベクター系列はまたは別のissueで作るかもしれません

2019-03-22 13:50 UTC, taishi-matsumura requested changes
仕事早いなぁ〜
クラス増えちゃったけど、元の処理があったところはめっちゃスッキリしましたね！ ✨

2019-03-22 13:50 UTC, taishi-matsumura commented on GameFramework/GameFramework/Collision/Collision.cpp
> +			for (int i = 0; CustomVertices::RECT_VERTICES_NUM < 4; ++i)
これ、ループに一度も入らなくない？
```suggestion
			for (int i = 0; i < CustomVertices::RECT_VERTICES_NUM; ++i)
```
では？

2019-03-22 13:54 UTC, taishi-matsumura commented on GameFramework/GameFramework/Collision/Collision.cpp
> +				D3DXVECTOR3 vec3Tmp = pVertices[(i + 1) % 4].m_pos - pVertices[i].m_pos;
了解です。費用対効果を考えながら進めて下さい！ 💪

2019-03-22 17:18 UTC, taishi-matsumura commented on GameFramework/GameFramework/Collision/Collision.cpp
> +			for (int i = 0; i < CustomVertex::RECT_VERTICES_NUM; ++i)
@yttmwork 
事後報告ですみませんが、ファーストクラスコレクションなぞ勧めてみたら早速やってくれました。どないでっしゃろ？
あと、Pimplなんかも紹介してます。こっちはファーストクラスコレクション以上にメリット・デメリット合わせ持ってる印象なので、「引き出しとして持っておいてくれたらいいなぁ」ぐらいの気持ちです。(以前勉強会でT井さんたちがPimplについて熱く語ってましたよね？)

2019-03-22 20:41 UTC, yttmwork commented on GameFramework/GameFramework/Collision/Collision.cpp
> +			for (int i = 0; i < CustomVertex::RECT_VERTICES_NUM; ++i)
@taishi-matsumura 
ファーストクラスコレクションを使ってる  
DirectX9Verticesなどのコードがすっきりして、いい感じですね～  

Pimpl紹介ありがとうございます！！  
勉強会でT井がイディオムは知っておいた方が良いという話しをしています。

2019-03-23 07:18 UTC, Kinoshita-Tatsuya requested changes

2019-03-23 07:18 UTC, Kinoshita-Tatsuya commented on GameFramework/GameFramework/GameFramework.h
> +			D3DXVECTOR3 mausePos(static_cast<float>(mousePoint.x), static_cast<float>(mousePoint.y), 0.0f);
綴り間違えてます

2019-03-23 08:00 UTC, Harutaka-Tsujino commented on GameFramework/GameFramework/Collision/Collision.cpp
> +			for (int i = 0; CustomVertices::RECT_VERTICES_NUM < 4; ++i)
そうです

2019-03-23 08:01 UTC, Harutaka-Tsujino commented on GameFramework/GameFramework/GameFramework.h
> +			D3DXVECTOR3 mausePos(static_cast<float>(mousePoint.x), static_cast<float>(mousePoint.y), 0.0f);
修正します

2019-03-23 08:08 UTC, Harutaka-Tsujino commented on GameFramework/GameFramework/GameFramework.h
> +			D3DXVECTOR3 mausePos(static_cast<float>(mousePoint.x), static_cast<float>(mousePoint.y), 0.0f);
mauseというよりはCursorだったのでそっちに合わせて修正しました

2019-03-24 13:11 UTC, Harutaka-Tsujino commented on GameFramework/GameFramework/Collision/Collision.cpp
> +			for (int i = 0; CustomVertices::RECT_VERTICES_NUM < 4; ++i)
修正しました

2019-03-24 13:18 UTC, taishi-matsumura approved these changes

2019-03-25 08:45 UTC, Kinoshita-Tatsuya approved these changes
確認しました。

2019-03-25 08:46 UTC, merged