回転角度のラッパクラスの作成
human-osaka-game-2018/GameFramework pull request #25
Opened 2019-03-09 15:01 UTC by Harutaka-Tsujino

Closes #24

2019-03-09 17:41 UTC, taishi-matsumura reviewed
Degreeクラスが非常に違和感あるのでコメントしました。
Radianクラスも同様です。

2019-03-09 17:41 UTC, taishi-matsumura commented on GameFramework/RotaionValue/Degree.h
> +		static const float m_ONE_CYCLE_AMOUNT;
定数のメンバに `m_` 付けるのはあまり見ないです

2019-03-09 17:41 UTC, taishi-matsumura commented on GameFramework/RotaionValue/Degree.cpp
> +		m_amount = amount;
結局符号だけの問題な気がするので、もう少しコードを共通化できそうです。
あと、そもそもこの関数はテストしましたか？期待通りに動かないと思うのですが…

2019-03-09 17:41 UTC, taishi-matsumura commented on GameFramework/RotaionValue/Degree.h
> +		/// <param name="min">最小値</param>
最大値・最小値に任意の値を指定できるというのは関数の仕様として無理がありませんか？
最大値・最小値共に、デフォルト引数の-180°〜180°のように制限が付くと思います。

2019-03-09 17:41 UTC, taishi-matsumura commented on GameFramework/RotaionValue/Degree.h
> +		/// <param name="min">最小値</param>
この関数がpublicである必要ありますか？

2019-03-09 17:41 UTC, taishi-matsumura commented on GameFramework/RotaionValue/Degree.h
> +		inline float Get() const
どうせ一定の360°の範囲に丸められた角度としてしか扱わないのであれば、その一定範囲の角度を返す関数と、利用者が指定した生の角度を返す関数を作ってあげた方が良いのでは？

2019-03-09 17:48 UTC, taishi-matsumura requested changes

2019-03-09 17:48 UTC, taishi-matsumura commented on GameFramework/RotaionValue/Radian.cpp
> +namespace BaseFactory
特にライブラリでは、クラスをnamespaceに入れるのはgoodだと思います。 👍 
ただし、namespaceの名前と実フォルダ名は合わせましょう。
https://ttsuki.github.io/styleguide/cppguide.ja.html#Namespace_Names

2019-03-09 17:54 UTC, taishi-matsumura requested changes

2019-03-09 17:54 UTC, taishi-matsumura commented on GameFramework/RotaionValue/Degree.h
> +		void FormatToMinBetweenMax(float amount, float max = m_ONE_CYCLE_AMOUNT * 0.5f, float min = -180.0f);
こんなけったいな名前にせずとも `Normalize` とかで良いのでは？
せめて `range` とか `fit` とかの単語を使って欲しいです。

2019-03-10 05:18 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/Degree.cpp
> +		m_amount = amount;
基底クラスを作成します

2019-03-10 05:18 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/Degree.h
> +		static const float m_ONE_CYCLE_AMOUNT;
消しておきます

2019-03-10 05:19 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/Degree.h
> +		/// <param name="min">最小値</param>
そうですね基本的に360度の差がないといけないのでそうなるように修正します

2019-03-10 05:21 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/Degree.h
> +		/// <param name="min">最小値</param>
一応ということで置いていましたが現状使用することがないのでprotectedにしておきます

2019-03-10 05:22 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/Degree.h
> +		inline float Get() const
そうですねそちらのほうが使い道が広がると思うのでそうします

2019-03-10 05:23 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/Radian.cpp
> +namespace BaseFactory
了解です

2019-03-10 05:24 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/Degree.h
> +		void FormatToMinBetweenMax(float amount, float max = m_ONE_CYCLE_AMOUNT * 0.5f, float min = -180.0f);
もう少し調べてみます

2019-03-10 06:43 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/Degree.cpp
> +		m_amount = amount;
テストを行い不具合を確認できたので修正しました

2019-03-10 06:53 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/Radian.cpp
> +namespace BaseFactory
今回はトップレベルの名前空間のみ使うよう予定なのでgameframeworkという名前空間にします

2019-03-10 07:13 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/Degree.h
> +		static const float m_ONE_CYCLE_AMOUNT;
修正しました

2019-03-10 07:14 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/Degree.h
> +		/// <param name="min">最小値</param>
最小値のみを設定するようにし最大値は最小値+360度となるようにしました

2019-03-10 07:14 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/Degree.h
> +		/// <param name="min">最小値</param>
修正しました

2019-03-10 07:14 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/Degree.h
> +		inline float Get() const
変更しました

2019-03-10 07:14 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/Radian.cpp
> +namespace BaseFactory
修正しました

2019-03-10 07:14 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/Degree.h
> +		void FormatToMinBetweenMax(float amount, float max = m_ONE_CYCLE_AMOUNT * 0.5f, float min = -180.0f);
Normalizeにしました

2019-03-10 07:47 UTC, taishi-matsumura approved these changes
とりあえず是正OKとし、アドバイスコメントだけ残しておきます。
修正するかどうかは任せます。

2019-03-10 07:47 UTC, taishi-matsumura commented on GameFramework/RotaionValue/RotationValue.h
> +		/// 最小値と最大値の間に角度を整える
「正規化」という言葉を使うと良いと思いますよ

2019-03-10 07:47 UTC, taishi-matsumura commented on GameFramework/RotaionValue/RotationValue.h
> +		inline float Get() const
「生の値」という意味で `Raw()` とか「正規化された値」という意味で `Normalized()` とかにすると、呼び出し元は
```
float raw = degree.Raw();
float normalized = degree.Normalized();
```
みたいになってわかりやすいと思います。

`RawValue()` とかも見かけますが、個人的には冗長な気がしますがまぁ好みですね。

2019-03-10 07:48 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/RotationValue.h
> +		/// 最小値と最大値の間に角度を整える
関数名との統一のため修正します

2019-03-10 07:49 UTC, taishi-matsumura commented on GameFramework/RotaionValue/Degree.cpp
> +		m_amount = amount;
C++、しかもゲームとなると自動テストが非常に書きにくいですが、こういう計算クラスとかには自動テストをどんどん導入していって下さい。
テストコードを書くコストはかかりますが、品質がグッと上がるはずです。

2019-03-10 07:50 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/RotationValue.h
> +		inline float Get() const
RawとNormalizedにします

2019-03-10 07:54 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/Degree.cpp
> +		m_amount = amount;
了解です

2019-03-10 15:58 UTC, taishi-matsumura requested changes
出力形式がexeになっているのも変だと思います。ライブラリじゃないの？

2019-03-10 15:58 UTC, taishi-matsumura commented on GameFramework/RotaionValue/Degree.h
> +#include <Window.h>
自動テスト用プロジェクトを作っていて気付きましたが、これって自作のヘッダですよね？
であれば
```suggestion
#include "Window.h"
```
ですね。

2019-03-10 16:29 UTC, taishi-matsumura requested changes

2019-03-10 16:29 UTC, taishi-matsumura commented on GameFramework/GameFramework.vcxproj
> +    <ClCompile Include="RotaionValue\RotationValue.cpp" />
自動テストのプロジェクトのビルドが通らず四苦八苦してたら…
```suggestion
    <ClCompile Include="RotationValue\RotationValue.cpp" />
```
フォルダ名のタイポ！！

2019-03-10 17:22 UTC, taishi-matsumura requested changes
標準ライブラリにせよDirectXにせよ内部的には全てラジアンで扱っているはずなので、
* 回転角度用便利クラス(単位はradian)
* それをdegreeで扱えるようにwrapしたもの

の2つの方が良かったかも知れませんね。

2019-03-10 17:22 UTC, taishi-matsumura commented on GameFramework/RotaionValue/RotationValue.h
> +		const float ONE_CYCLE_AMOUNT;
子クラスから設定してもらうようになったので、これは定数では無いですね。
```suggestion
		float m_oneCycleAmount;
```
で良いのでは？

また、アクセスレベルもpublicでは無いのでは？

2019-03-10 17:22 UTC, taishi-matsumura commented on GameFramework/RotaionValue/RotationValue.cpp
> +		}
「共通化できるのでは？」という指摘は基底クラスを作るという意味ではなく、ここの2つのif文について
```
		float adjustVal;
		if (m_min <= amount && amount <= m_max) {
			adjustVal = 0.0f;
		}
		else {
			adjustVal = amount < m_min ? ONE_CYCLE_AMOUNT : -ONE_CYCLE_AMOUNT;
		}

		m_normalizedAmount = amount + adjustVal;
```
くらいにスッキリさせられないか検討して欲しいという意図でした。

2019-03-10 17:22 UTC, taishi-matsumura commented on GameFramework/RotaionValue/Radian.h
> +		Radian(float amount, float min) :RotationValue(amount, min, D3DX_PI) {};
本当にテストしましたか？
一周(360°)は2πラジアンでは無いですか？

2019-03-10 17:29 UTC, taishi-matsumura commented on GameFramework/RotaionValue/RotationValue.cpp
> +		}
人間、謎の似て非なる式がたくさん出てきたら読む気が失せるものです。
intへのキャストの必要性もよくわかりません。

今回のケースであれば、
* amountが範囲内であればそのまま
* 最小値未満であれば一周ぶん足す
* 最大値より大きければ一周ぶん引く
* そのようにして範囲内に正規化された値をインスタンス変数として保持しておく

という意図が読み取れるコードを書くべきです。
私が提案したコートがベストだとは思いませんし人によっては読み辛いと感じる人も居るはずですが、元のコードよりはマシだと思いますよ。

わかり辛い式にならざるを得ないのなら、その理由をコメントしておきましょう。

2019-03-10 20:25 UTC, taishi-matsumura requested changes
「貸してみろ！」と思って自分でも作ってみましたが、ムズいですね…
偉そうなこと言ってすみません。お疲れ様ですm(_ _)m

2019-03-10 20:25 UTC, taishi-matsumura commented on GameFramework/RotaionValue/RotationValue.cpp
> +		m_max = m_min + ONE_CYCLE_AMOUNT;
最小値・最大値がインスタンス生成後は不変なのであればコンストラクタで設定してしまいましょう。
この関数はそこかしこで呼ばれるようなので、その度にメンバ変数にセットし直すのもイヤですし。

2019-03-10 20:25 UTC, taishi-matsumura commented on GameFramework/RotaionValue/RotationValue.cpp
> +		}
あ、2周以上ずれているときのために割り算して整数にキャストしているのですね。なるほど ！
…と思ってテストしてみましたが、最小値が0じゃないと動かないみたいです。
テストコードとテスト結果を貼っておきます。

テストコード
```
// 0.0～2.0pi、範囲内
TEST(RadianTest, Normalized1) {
	Radian rad(0.25f * D3DX_PI, 0.0f);
	EXPECT_FLOAT_EQ(0.25f * D3DX_PI, rad.Normalized());
}

// 0.0～2.0pi、最小値未満、1周進める
TEST(RadianTest, Normalized2) {
	Radian rad(-0.25f * D3DX_PI, 0.0f);
	EXPECT_FLOAT_EQ(1.75f * D3DX_PI, rad.Normalized());
}

// 0.0～2.0pi、最大値より大、1周戻す
TEST(RadianTest, Normalized3) {
	Radian rad(2.25f * D3DX_PI, 0.0f);
	EXPECT_FLOAT_EQ(0.25f * D3DX_PI, rad.Normalized());
}

// 0.0～2.0pi、最大値より大、2周戻す
TEST(RadianTest, Normalized4) {
	Radian rad(4.25f * D3DX_PI, 0.0f);
	EXPECT_FLOAT_EQ(0.25f * D3DX_PI, rad.Normalized());
}

// 0.0～2.0pi、最小値未満、2周進める
TEST(RadianTest, Normalized5) {
	Radian rad(-2.25f * D3DX_PI, 0.0f);
	EXPECT_FLOAT_EQ(1.75f * D3DX_PI, rad.Normalized());
}

// 0.5～2.5pi、最小値未満、1周進める
TEST(RadianTest, Normalized6) {
	Radian rad(0.25f * D3DX_PI, 0.5f * D3DX_PI);
	EXPECT_FLOAT_EQ(2.25f * D3DX_PI, rad.Normalized());
}

// 0.5～2.5pi、最大値より大、1周戻す
TEST(RadianTest, Normalized7) {
	Radian rad(2.75f * D3DX_PI, 0.5f * D3DX_PI);
	EXPECT_FLOAT_EQ(0.75f * D3DX_PI, rad.Normalized());
}

// 0.5～2.5pi、最小値未満、2周進める
TEST(RadianTest, Normalized8) {
	Radian rad(-1.75f * D3DX_PI, 0.5f * D3DX_PI);
	EXPECT_FLOAT_EQ(2.25f * D3DX_PI, rad.Normalized());
}

// 0.5～2.5pi、最大値より大、2周戻す
TEST(RadianTest, Normalized9) {
	Radian rad(4.75f * D3DX_PI, 0.5f * D3DX_PI);
	EXPECT_FLOAT_EQ(0.75f * D3DX_PI, rad.Normalized());
}
```

テスト結果
![image](https://user-images.githubusercontent.com/12269762/54090918-e5cf6e00-43bc-11e9-9566-bfe04daf61e0.png)
Normalized4が失敗しているのは浮動小数の誤差の問題なので一旦置いておくとして、Normalized8が失敗しているのはマズいですね。
テストケースももう少し必要そうです。

2019-03-11 11:31 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/Degree.h
> +#include <Window.h>
Windows.hのつもりが間違っていましたしかし現在不要なため削除しました

2019-03-11 11:45 UTC, Harutaka-Tsujino commented on GameFramework/GameFramework.vcxproj
> +    <ClCompile Include="RotaionValue\RotationValue.cpp" />
フォルダ名修正しました

2019-03-11 11:50 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/RotationValue.h
> +		const float ONE_CYCLE_AMOUNT;
そうします

2019-03-11 11:54 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/RotationValue.h
> +		const float ONE_CYCLE_AMOUNT;
degreeとradian でまた別に作成しました

2019-03-11 11:55 UTC, taishi-matsumura requested changes

2019-03-11 11:55 UTC, taishi-matsumura commented on GameFramework/RotationValue/RotationValue.h
> +		const float m_MAX = NULL;
定数にはプレフィクス付けないことにしたんですよね？

2019-03-11 11:55 UTC, taishi-matsumura commented on GameFramework/RotationValue/RotationValue.h
> +		const float m_MAX = NULL;
NULLは「無効なアドレス」という意味です。
floatの変数に突っ込むなど、言語道断です！ 💩

2019-03-11 11:57 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/RotationValue.cpp
> +		m_max = m_min + ONE_CYCLE_AMOUNT;
修正しました

2019-03-11 11:58 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/Radian.h
> +		Radian(float amount, float min) :RotationValue(amount, min, D3DX_PI) {};
修正しました

2019-03-11 11:58 UTC, Harutaka-Tsujino commented on GameFramework/RotationValue/RotationValue.h
> +		const float m_MAX = NULL;
修正します

2019-03-11 12:02 UTC, taishi-matsumura commented on GameFramework/RotationValue/RotationValue.h
> +		const float m_oneCycleAmount = 0.0f;
constで初期値も設定されているので定数なのかと思いきや、コンストラクタで子クラスから渡された値をセットするんですね…

@yttmwork 
気持ち悪すぎるけどC++的には仕方無いのかなぁ。
C#の `readonly` みたいなのって無いんでしたっけ？

2019-03-11 12:02 UTC, Harutaka-Tsujino commented on GameFramework/RotationValue/RotationValue.h
> +		const float m_MAX = NULL;
未定の値ということでNULLを使っていて無効なアドレスはnullptrにしていました
基本的に0を代入するときは基本が0の時に使っていました
ただややこしくなるので0.0fを代入するようにしました

2019-03-11 12:03 UTC, Harutaka-Tsujino commented on GameFramework/RotationValue/RotationValue.h
> +		const float m_oneCycleAmount = 0.0f;
調べてみましたができなさそうです

2019-03-11 12:08 UTC, taishi-matsumura commented on GameFramework/RotationValue/RotationValue.h
> +		const float m_oneCycleAmount = 0.0f;
やっぱりそうですか。残念ですね。

このクラスにとってはconstでは無いのと、private変数なので外部から弄られることも無いのでconst外しませんか？
constは宣言時に初期化でき、且つその後変わらないものに付けるべきだと思うんですよねー

2019-03-11 12:08 UTC, Harutaka-Tsujino commented on GameFramework/RotationValue/RotationValue.h
> +		const float m_oneCycleAmount = 0.0f;
外しました

2019-03-11 12:14 UTC, Harutaka-Tsujino commented
現在テストを行っているので修正に時間がかかると思います

2019-03-11 12:15 UTC, taishi-matsumura commented on GameFramework/RotationValue/RotationValue.h
> +		const float m_MAX = NULL;
これも `m_oneCycleAmount ` 同様、const付けるのは微妙なやつじゃないですか？

2019-03-11 12:16 UTC, Harutaka-Tsujino commented on GameFramework/RotationValue/RotationValue.h
> +		const float m_MAX = NULL;
そうですね修正します

2019-03-11 12:17 UTC, taishi-matsumura commented
> 現在テストを行っているので修正に時間がかかると思います

ライブラリの中でも特に計算処理の部分なので入念にテストしておきましょう。
幸い、他に依存しているクラスも無くテストしやすいですし。
大変だと思いますが、頑張って！ 💪

2019-03-11 12:20 UTC, taishi-matsumura commented
チームメンバーはもちろんですが、それ以外の人でも誰かテストコードくらい書いてあげたらいいのに。
辻野一人で可哀想やわ 😢

2019-03-11 12:21 UTC, masami-sugao commented on GameFramework/RotationValue/RotationValue.h
> +		const float m_oneCycleAmount = 0.0f;
もしくは、宣言時に値を代入するのを止めてはどうでしょう？
constを付けていればメンバイニシャライザ以外の場所での代入を防げるのと、処理の途中で値が変わらないことを明示できるので、付ける意味はあると思います。

2019-03-11 12:30 UTC, taishi-matsumura commented on GameFramework/RotationValue/RotationValue.h
> +		const float m_oneCycleAmount = 0.0f;
ですね。宣言時に謎の値で初期化されていることが混乱の元になっている気がします。
const付けるのであればソースコード上でも不変であるべきだし、昔ながらのC++的なコードにするのであれば非constでも良いかと。

2019-03-11 12:36 UTC, taishi-matsumura reviewed
C++のキャストは長いので極力減らしたいですね。
都度書く必要があるようなら仕方無いです。

2019-03-11 12:36 UTC, taishi-matsumura commented on GameFramework/RotationValue/RotationValue.cpp
> +			amount -= static_cast<int>(amount) / static_cast<int>(m_oneCycleAmount) * m_oneCycleAmount;
```suggestion
			amount -= static_cast<int>(amount / m_oneCycleAmount) * m_oneCycleAmount;
```
ではダメですか？

2019-03-11 12:51 UTC, yttmwork commented on GameFramework/RotationValue/RotationValue.h
> +		const float m_oneCycleAmount = 0.0f;
@taishi-matsumura 
お疲れ様です。
もう結論も出てしまっていますが、
@Harutaka-Tsujinoが書いているように、
C++にはreadonlyはまだなかったはずです。
念のためC++20で導入されるかもと思って調べてみましたが、
今のところなさそうです。

2019-03-11 14:19 UTC, taishi-matsumura reviewed
コメントとか、勢いで直しちゃって下さい

2019-03-11 14:19 UTC, taishi-matsumura commented on GameFramework/RotationValue/Degree.h
> +		/// </remarks>
こちらには度数の例だけで良いと思います。
同様に、Radianクラスの方はradianの例だけで良いと思います。

2019-03-11 14:19 UTC, taishi-matsumura commented on GameFramework/RotationValue/Degree.h
> +		/// </remarks>
改行タグを入れたのなら
```
/// 範囲は円を一周以上していてはいけない 例:-370度, -2.5 * pi等</br>
/// 180度を設定すると最大値が一周するのでこれも不可
```
みたいにコメントも改行しておいた方がわかりやすいです。
将来的にhtmlを書くときも同様に。

で、ここはxmlコメントなので `</br>` みたいなhtmlのタグを打つよりは `<para>` タグの方が良いと思いますよ。
http://sorceryforce.net/ja/visualstudio/xmlcommentnewline

2019-03-11 14:19 UTC, taishi-matsumura commented on GameFramework/RotationValue/RotationValue.h
> +		/// </remarks>
c'torがpublicになっていますが、 `Degree` `Radian` だけじゃなく基底クラスの `RotationValue` も利用者が直接生成可能なのですか？

2019-03-11 14:19 UTC, taishi-matsumura commented on GameFramework/RotationValue/Radian.h
> +	public:
行末に謎の空白。

2019-03-11 14:19 UTC, taishi-matsumura commented on GameFramework/RotationValue/RotationValue.h
> +		virtual ~RotationValue() =0;
```suggestion
		virtual ~RotationValue() = 0;
```
どこにスペース入れるかは統一しておきましょう。

2019-03-11 14:24 UTC, taishi-matsumura commented on GameFramework/RotationValue/RotationValue.h
> +		const float m_oneCycleAmount = 0.0f;
@Harutaka-Tsujino 
念のため確認です。
> 宣言時に謎の値で初期化されていることが混乱の元になっている気がします。

は理解した上で、
> constを付けていればメンバイニシャライザ以外の場所での代入を防げるのと、処理の途中で値が変わらないことを明示できるので、付ける意味はあると思います。

は採用せず、
> 昔ながらのC++的なコードにするのであれば非constでも良いかと。

を採用という方針なのですね？

2019-03-11 14:27 UTC, Harutaka-Tsujino commented on GameFramework/RotationValue/Degree.h
> +		/// </remarks>
了解です

2019-03-11 14:28 UTC, Harutaka-Tsujino commented on GameFramework/RotationValue/RotationValue.h
> +		/// </remarks>
privateにします

2019-03-11 14:29 UTC, taishi-matsumura commented on GameFramework/RotaionValue/RotationValue.cpp
> +		}
@Harutaka-Tsujino 
最後が「テストNGでした」という指摘なので、「テスト通りました」というレスを貰えればResolvedにします。

2019-03-11 14:31 UTC, taishi-matsumura commented on GameFramework/RotationValue/RotationValue.h
> +		/// </remarks>
派生クラスあるのにprivateにしちゃってもコンパイル通るの？

2019-03-11 14:33 UTC, taishi-matsumura commented on GameFramework/RotationValue/Degree.h
> +		/// </remarks>
ついでに言うと、「範囲は円を一周以上していてはいけない」は日本語として変ですね。

2019-03-11 15:55 UTC, Harutaka-Tsujino commented on GameFramework/RotationValue/RotationValue.h
> +		const float m_oneCycleAmount = 0.0f;
@taishi-matsumura 
デバッグのために基本的にconstであれ宣言時に初期化を行っているので
非constにして混乱を防ぐようにします

2019-03-11 15:56 UTC, Harutaka-Tsujino commented on GameFramework/RotationValue/RotationValue.h
> +		/// </remarks>
protectedになるよう修正しました

2019-03-11 15:56 UTC, Harutaka-Tsujino commented on GameFramework/RotationValue/Radian.h
> +	public:
修正しました

2019-03-11 15:57 UTC, Harutaka-Tsujino commented on GameFramework/RotationValue/RotationValue.h
> +		virtual ~RotationValue() =0;
了解です
修正しました

2019-03-11 15:57 UTC, Harutaka-Tsujino commented on GameFramework/RotationValue/Degree.h
> +		/// </remarks>
今日メンバーに相談してみます

2019-03-11 15:57 UTC, taishi-matsumura commented on GameFramework/RotationValue/RotationValue.h
> +		const float m_oneCycleAmount = 0.0f;
了解です

2019-03-11 16:00 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/RotationValue.cpp
> +		}
了解です

2019-03-11 16:09 UTC, taishi-matsumura commented on GameFramework/RotationValue/RotationValue.h
> +		virtual ~RotationValue() =0;
OKです。デストラクタを純粋仮想にする意味がよくわかりませんが…
(最近、僕の知らないC++の機能が多過ぎて困っています。何か特別な意味があるならまた教えて下さい…)

2019-03-11 16:26 UTC, taishi-matsumura commented
> 出力形式がexeになっているのも変だと思います。ライブラリじゃないの？

この件、どうなってますか？

2019-03-11 16:49 UTC, taishi-matsumura requested changes
たぶん別のプルリクで追加したファイルだと思いますが、それらがコンパイル対象として設定されているせいでビルドが通りません。
プロジェクトから除外するか、せめて「ファイルのプロパティ→ビルドから除外→はい」と設定しておいて下さい。

2019-03-11 16:49 UTC, taishi-matsumura commented on GameFramework/GameFramework.vcxproj
> +    <ClCompile Include="GameFramework\GameFramework.cpp" />
不要と思われます

2019-03-11 16:49 UTC, taishi-matsumura commented on GameFramework/GameFramework.vcxproj
> +    <ClCompile Include="Algorithm\Algorithm.cpp" />
不要と思われます

2019-03-11 17:02 UTC, taishi-matsumura requested changes
五月雨で指摘しちゃって本当にすみません。
叩けばいくらでも埃出ますなぁ…

2019-03-11 17:02 UTC, taishi-matsumura commented on GameFramework/GameFramework.vcxproj.filters
> +    <ClCompile Include="RotaionValue\RotationValue.cpp">
ディレクトリ名のタイポの修正、まだ残ってますね。
ソリューションエクスプローラで見ればわかると思いますが、今回追加した角度関係のクラス群がRotationValueフィルタの中では無くプロジェクト直下に居るはず。
修正お願いします。

2019-03-11 17:59 UTC, taishi-matsumura reviewed
質問でーす

2019-03-11 17:59 UTC, taishi-matsumura commented on GameFramework/RotationValue/Degree.h
> +		const Degree operator+(const Degree& rhs) const
`Radian` と `Degree` のこの辺の各演算子オーバーロードですが、 結局中身は同じなので `RotationValue` にtemplateで持ってしまってはどうでしょう？
ざーっくりテストしてみましたが、動きそうですよ。

※代入演算子はデフォルトのものが優先的に呼ばれるため無理でした
参考:[template と operator = を組み合わせてみたところ死亡（スペランカー先生のように）
](https://ir9ex.hatenablog.jp/entry/20080320/1206023405)

2019-03-11 17:59 UTC, taishi-matsumura commented on GameFramework/RotationValue/Degree.h
> +		Degree(float amount = 0.0f, float min = -180.0f) :RotationValue(amount, min, ONE_CYCLE_AMOUNT) {};
このような「デフォルト引数を除けば引数1個」のコンストラクタは変換コンストラクタとして機能してしまいます。
つまり、
```
Degree deg = 45.0f;
```
と書くと暗黙的に
```
Degree deg(45.0f);
```
としてコンパイルされ、結果として
```
Degree::Degree(float amount = 0.0f, float min = -180.0f)
```
が呼ばれてしまいますので注意して下さい。

```
Degree deg = 45.0f;
```
のような宣言方法を意図的に可能にしているのであれば良いのですが、そうでなければexplicitを付けておいた方が安全だと思います。

2019-03-11 18:31 UTC, Harutaka-Tsujino commented on GameFramework/RotationValue/Degree.h
> +		const Degree operator+(const Degree& rhs) const
templateのことは考えれていませんでした
テストが完了したらやってみます

2019-03-11 18:31 UTC, Harutaka-Tsujino commented on GameFramework/RotationValue/Degree.h
> +		Degree(float amount = 0.0f, float min = -180.0f) :RotationValue(amount, min, ONE_CYCLE_AMOUNT) {};
今回は意図しています

2019-03-11 18:35 UTC, Harutaka-Tsujino commented on GameFramework/GameFramework.vcxproj.filters
> +    <ClCompile Include="RotaionValue\RotationValue.cpp">
修正しました

2019-03-11 18:41 UTC, Harutaka-Tsujino commented on GameFramework/GameFramework.vcxproj
> +    <ClCompile Include="GameFramework\GameFramework.cpp" />
修正しました

2019-03-11 18:41 UTC, Harutaka-Tsujino commented on GameFramework/GameFramework.vcxproj
> +    <ClCompile Include="Algorithm\Algorithm.cpp" />
修正しました

2019-03-11 18:42 UTC, Harutaka-Tsujino commented
> > 出力形式がexeになっているのも変だと思います。ライブラリじゃないの？
> 
> この件、どうなってますか？

このプルリクエストが終了したら修正します

2019-03-11 18:48 UTC, taishi-matsumura commented on GameFramework/RotationValue/Degree.h
> +		const Degree operator+(const Degree& rhs) const
operatorの引数や戻り値を基底クラスで扱って良いのならtemplateにする必要は無いんですけどね。
その辺りはライブラリの作り易さと使い易さのトレードオフですねぇ。

まぁ、ほぼ同じコードを兄弟クラスで書いているのはDRYの原則に反しているので共通化できそうならトライしてみて下さい。
別プルリクで検討するのもアリだと思います。

2019-03-11 19:11 UTC, Harutaka-Tsujino commented on GameFramework/RotaionValue/RotationValue.cpp
> +		}
処理を修正し
度数法ですがテスト行い確認できました

2019-03-12 03:01 UTC, taishi-matsumura commented on GameFramework/RotaionValue/RotationValue.cpp
> +		}
お疲れ様でした 🍵 

先程口頭で伝えましたが、Google C++ Testing Frameworkが秒殺で導入できます。
こういうクラスなんかは絶好の出番なので是非！

2019-03-12 03:23 UTC, taishi-matsumura approved these changes

2019-03-12 05:31 UTC, taishi-matsumura commented
承認しておきました。
コミットを整理したらマージしちゃって下さい。

2019-03-12 15:21 UTC, merged