カラー構造体の作成
human-osaka-game-2018/GameFramework pull request #48
Opened 2019-03-13 16:31 UTC by Harutaka-Tsujino

カラーコードの分解合成や
色を割ったりすることもできる
一色の最大値は255以上保存できる

Closes #32

2019-03-13 16:49 UTC, rikita-fujizono approved these changes
確認しました。

2019-03-13 16:49 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +		Color() {};
デフォルトコンストラクタ要りますか？
つまり、「色を管理する入れ物は作ったけど何色かは未定」という状態を許容しますか？ということです。

一般論ですが、
* パラメータが設定されていないとクラスとして機能しない
* インスタンス生成時にそのパラメータは確定するはず

みたいなクラスは、不定な状態を作らないためにもデフォルトコンストラクタを蓋してしまう方が良いです。
加えて、中身はimmutable(不変)にしてしまった方がクラスとしては安定し安全です。
* インスタンス生成時にパラメータが決定し、そいつが死ぬまで中身は変わらない
* 中身が変わるということは別物なので、別インスタンスを作り直す

という発想です。

特に今回のようなデータクラスを作成する際は使い易さとコードのロバストネス(堅牢性)とを天秤に掛けて検討するようにして欲しいです。

2019-03-13 16:49 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +		Color(DWORD alpha, DWORD red, DWORD green, DWORD blue)
ARGBで4バイトなのであれば、それぞれは1バイトなのでは？
`GetColorCode()` や各色を保持しているメンバ変数も同様です。

それらをDWORD型にしている理由があれば教えて下さい。

2019-03-13 16:51 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +		Color() {};
今回は色にデフォルトで255を入れているのでデフォルトのコンストラクタを作りました

2019-03-13 16:53 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +		Color() {};
なるほど。透過ゼロの真っ白ですね？
では、利用者にわかるようにデフォルトコンストラクタにその旨コメントしておきましょう。

2019-03-13 16:54 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +		Color(DWORD alpha, DWORD red, DWORD green, DWORD blue)
色を足し引きする際に0xFF858585+0xFF545454等がオーバーフローしてしまい
色のアベレージを求める際におかしな値を返してしまう可能性があることと
HDRのことを少し意識して余分にとっています

2019-03-13 16:55 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +		Color() {};
了解です

2019-03-13 17:04 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +		Color(DWORD alpha, DWORD red, DWORD green, DWORD blue)
なるほど。
であれば `GetColorCode()` が変な感じしますね(例えばRに300が入っていても255として返ってくる)。
HDRで値の上限が増えるのはminからmaxをより細かく表現するためのはずなので、それをHDRの255段階として返すのであれば変換処理が必要ですね。

2019-03-13 17:08 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +		Color(DWORD alpha, DWORD red, DWORD green, DWORD blue)
* 利用者はHDRでもSDRでも利用可能
* 内部的にはHDRで管理し、必要に応じてSDRと相互に変換

くらいにしないと色々矛盾しますよ。

2019-03-13 17:15 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +		Color(DWORD alpha, DWORD red, DWORD green, DWORD blue)
> 色を足し引きする際に0xFF858585+0xFF545454等がオーバーフローしてしまい

こういうのはI/F部分の型を変えるのではなく内部での計算ロジックを工夫すべきであり、そのクラス内部の都合で利用者を振り回してはいけません。
そのような対応が時間的に厳しいのであれば、(できるできる詐欺になってしまうので)そもそもそういう機能を公開すべきでは無いです。

2019-03-13 17:47 UTC, taishi-matsumura requested changes
便利クラスとしては色々中途半端過ぎるので `Request changes` にしておきます。
高機能だけど色々破綻してるものよりも、シンプルだが矛盾無く小綺麗に纏まってるものの方が利用者を混乱させないのでよっぽどマシです。

高みを目指す姿勢は最高に ❤️  だと思うので、うまく落とし所を見付けていきましょう！ 💪 
制限事項をコメントに明記するだけでも全然変わりますよ〜

2019-03-13 19:26 UTC, taishi-matsumura requested changes
テストコード書いてて色々気になったので。

[テストの方](49) は仕様がどうあるべきかわからず詰みました。
テストコード内にコメント書いたので 44edb19 を参照して下さい。

2019-03-13 19:26 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +				static_cast<BYTE>(m_blue));
static_castすると上位3バイトは捨てられてしまいますが、そういう仕様ですか？
もしARGBの各値を0〜255に変換するとしても、operator[] で返ってくる値と異なるのは仕様として違和感ありませんか？

2019-03-13 19:26 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +				break;
戻り値を返さないパスがある旨のwarningが出ていると思います。
ここに入っても何か値を返すよう修正しましょう。

2019-03-13 19:26 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +			for (int i = 0; i < COLOR_COMPONENTS_NUM_MAX; ++i)
こんなC言語ライクなコードにせず、コンテナ使って全件回しましょう。
で、 `HOGE_MAX` なんていう不細工な列挙子(これはC言語のテクニックです)を追放しましょう。

2019-03-13 19:26 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +		enum class COLOR_COMPONENTS
C++11は自信無いのですが、使うときは `Color::COLOR_COMPONENTS::ALPHA` みたいになるのでは？
だとしたら冗長なので
```suggestion
		enum class COMPONENTS
```
で良くないですか？

僕は他のやり方がわからなかったので、テストコードではエイリアス作りました。

2019-03-14 01:43 UTC, Harutaka-Tsujino commented
今回の仕様としてHDRからSDRの変換が難しそうなのでいったん廃止し、一色の上限を255に修正します。
色の平均のとりかたについては新たに関数を実装しますｍ

2019-03-14 01:46 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +			for (int i = 0; i < COLOR_COMPONENTS_NUM_MAX; ++i)
std:arrayを使うようにします

2019-03-14 02:54 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +			for (int i = 0; i < COLOR_COMPONENTS_NUM_MAX; ++i)
おぉ、C++11で追加されたアレですか…
固定長配列なので生の配列と同様初期化時に要素数を指定する必要があって面倒臭い気がしますね。

2019-03-14 04:25 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +				static_cast<BYTE>(m_blue));
m_alpha等をDWORDからBYTEに直しました

2019-03-14 04:25 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +				break;
返すようにしました

2019-03-14 04:26 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +			for (int i = 0; i < COLOR_COMPONENTS_NUM_MAX; ++i)
const vectorにしました

2019-03-14 04:26 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +			for (int i = 0; i < COLOR_COMPONENTS_NUM_MAX; ++i)
iを扱うところがあったのでfor_eachは使っていません

2019-03-14 04:27 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +		enum class COLOR_COMPONENTS
修正しました

2019-03-14 04:27 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +		Color(DWORD alpha, DWORD red, DWORD green, DWORD blue)
いったんHDRは考えないように修正しました

2019-03-14 04:43 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +		/// <param name="colorComponent">アクセスする色のCOMPONENTS</param>
こういうところで `<seealso>` とか使うと良いと思うのです

2019-03-14 04:43 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +				return m_blue;
これってfail-safe処理ですよね？
`m_blue` を返すのはどうかと思いますし、引数がおかしいということ(たぶんコーディングミスのはず)がわかるようにすべきでは？

2019-03-14 04:43 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +			const int COMPONENTS_MAX = static_cast<int>(colorComponents.size());
下のfor文の中に `colorComponents.size()` が出てくるのを避けて一時変数に入れたのだと思いますが、こういうのは普通constにしないです。

2019-03-14 04:43 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +				(*this)[colorComponents[i]] = static_cast<BYTE>((colorCode & 0xFF000000) >> ONE_COLOR_BITS * (COMPONENTS_MAX - 1 - i));
これ、ちゃんと動くんかなぁ…

2019-03-14 04:43 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +			for (int i = 0; COMPONENTS_MAX; ++i)
インデックスが欲しいから普通のfor文なんですね。
 [先頭からのdistanceを取得する方法](http://yamayatakeshi.jp/c11っぽくstdvectorでindexをfindしたい/) もありますので検討してみて下さい(読み易いかどうかは微妙ですが…)

2019-03-14 04:47 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +				static_cast<BYTE>(m_blue  * rhs));
昨夜も指摘しましたが、 0xFF を超えたものをBYTEにstatic_castすると最下位2バイトのみに切り捨てられてしまいますが、それで大丈夫ですか？

2019-03-14 04:49 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +				return m_blue;
enum classは明示的に型キャストしなければいけないので
コーディングミスが起こらないと想定しています

2019-03-14 04:49 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +			const int COMPONENTS_MAX = static_cast<int>(colorComponents.size());
そうなんですね修正します

2019-03-14 04:50 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +				static_cast<BYTE>(m_blue  * rhs));
HDRは考えないようにしたのでそれで大丈夫です

2019-03-14 04:56 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +				static_cast<BYTE>(m_blue  * rhs));
えーと、
1. 赤に0xC0(192) が入っている
1. 4倍すると、 `m_red   * rhs` の計算結果は0x300(768)になる
1. 0x300をBYTE型にstatic_castすると最下位2バイトのみになるので、結果は0x00

これでOK？

2019-03-14 04:59 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +				return m_blue;
では、0x00か0xFFを返すようにして `// faile-safe` とか `// ここには絶対到達しない` みたいなコメント入れておきましょう。(絶対到達しないとは言い切れないですけど…)

2019-03-14 05:05 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +		/// <param name="colorComponent">アクセスする色のCOMPONENTS</param>
previewで型のところが参照みたいになっていないのでつけなくてよさそうです

2019-03-14 05:10 UTC, ToshiyaMatsuoka commented on GameFramework/Color/Color.h
> +		/// <param name="colorComponent">アクセスする色のCOMPONENTS</param>
リンクさせる場合、
```
	/// <param name="Color::colorComponent">アクセスする色のCOMPONENTS</param>
```
になるのでは？

2019-03-14 05:11 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +		/// <param name="colorComponent">アクセスする色のCOMPONENTS</param>
そこは大丈夫なようです

2019-03-14 05:19 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +				static_cast<BYTE>(m_blue  * rhs));
static_castの処理をずっと勘違いしてました修正します

2019-03-14 05:27 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +				static_cast<BYTE>(m_blue  * rhs));
テストしーやー 😑

2019-03-14 05:30 UTC, ToshiyaMatsuoka commented on GameFramework/Color/Color.h
> +		/// <param name="colorComponent">アクセスする色のCOMPONENTS</param>
勘違いしてました。
リンクは`<seealso>`で貼るが、`<param>`ではリンクは貼れない。

`<seealso>`無いと「COMPONENTS」って何？ってことになるので入れるほうがよろしいかと

2019-03-14 05:31 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +		/// <param name="colorComponent">アクセスする色のCOMPONENTS</param>
型のところから飛ぶことってできないですか？

2019-03-14 05:35 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +				static_cast<BYTE>(m_blue  * rhs));
修正しました

2019-03-14 05:36 UTC, masami-sugao commented on GameFramework/Color/Color.h
> +		/// <param name="colorComponent">アクセスする色のCOMPONENTS</param>
```xml
<param name="colorComponent">アクセスする色の<see cref=“COMPONENTS” /></param>
```
と書けば、COMPONENTSにリンクが貼られます。

でも引数の型自体がDoxygenに出力されるので、同じ型であれば `see` や `see also` を使ってCOPONENTSのリンクを作らなくても、ドキュメントを参照する人の利便性は損なわれません。

2019-03-14 05:45 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +		/// <param name="colorComponent">アクセスする色のCOMPONENTS</param>
同じスコープ内に存在しているものは今回はsee等を基本的には使わずに進みます
別のクラスなどにあるものはリンクを張るようにします

2019-03-14 05:45 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +				return m_blue;
修正しました

2019-03-14 05:48 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +				(*this)[colorComponents[i]] = static_cast<BYTE>((colorCode & 0xFF000000) >> ONE_COLOR_BITS * (COMPONENTS_MAX - 1 - i));
見直したら動かないので修正します

2019-03-14 05:50 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +				(*this)[colorComponents[i]] = static_cast<BYTE>((colorCode & 0xFF000000) >> ONE_COLOR_BITS * (COMPONENTS_MAX - 1 - i));
テストしーやー 👿

2019-03-14 05:51 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +				(*this)[colorComponents[i]] = static_cast<BYTE>((colorCode & 0xFF000000) >> ONE_COLOR_BITS * (COMPONENTS_MAX - 1 - i));
ゲーム作成の準備を早めに終わらせたいのでお許しください

2019-03-14 05:55 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +				(*this)[colorComponents[i]] = static_cast<BYTE>((colorCode & 0xFF000000) >> ONE_COLOR_BITS * (COMPONENTS_MAX - 1 - i));
はい、「とりあえず枠だけ作って作業を進める」というのも全然アリだと思います。
ただ、そのノリで作ったものを就活に持って行って「便利クラス作りました！」って言っても恥かくだけやから注意してね。
それまでのどこかのタイミングではやらないとねー

2019-03-14 05:57 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +				(*this)[colorComponents[i]] = static_cast<BYTE>((colorCode & 0xFF000000) >> ONE_COLOR_BITS * (COMPONENTS_MAX - 1 - i));
とりあえず枠づくりが終わって暇な時間が出たらテストコードを書く予定です

2019-03-14 06:09 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +				(*this)[colorComponents[i]] = static_cast<BYTE>((colorCode & 0xFF000000) >> ONE_COLOR_BITS * (COMPONENTS_MAX - 1 - i));
クラスの仕様もある程度固まったっぽいし、ちょっとずつテスト書いていくわー 💪

2019-03-14 06:10 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +				return m_blue;
goodです 👍

2019-03-14 06:12 UTC, masami-sugao commented on GameFramework/Color/Color.h
> +		/// <param name="colorComponent">アクセスする色のCOMPONENTS</param>
因みに、 `see`  でリンクにしておくと、型名が変更になった時にVisualStudioのリファクタリング機能でXMLコメント部分も変更してくれるというメリットがあります。
C++でもこの機能が働くのかはわからないですが…。

2019-03-14 06:26 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +			const int COMPONENTS_MAX = static_cast<int>(colorComponents.size());
修正しました

2019-03-14 06:27 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +				(*this)[colorComponents[i]] = static_cast<BYTE>((colorCode & 0xFF000000) >> ONE_COLOR_BITS * (COMPONENTS_MAX - 1 - i));
修正しました動くと思います

2019-03-14 06:28 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +			for (int i = 0; COMPONENTS_MAX; ++i)
今回は見にくくなるので見送ります

2019-03-14 06:42 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +				(*this)[colorComponents[i]] = static_cast<BYTE>((colorCode & 0xFF000000) >> ONE_COLOR_BITS * (COMPONENTS_MAX - 1 - i));
はーい、確認していきまーす

2019-03-14 06:56 UTC, taishi-matsumura approved these changes
これで一旦OKにして次に進みましょうか。
#49 の作業内容を取り込んでおいたので、併せてコミットの整理をお願いします。

2019-03-14 07:24 UTC, merged

2019-03-16 11:07 UTC, taishi-matsumura reviewed
見れば見るほど、クラスと構造体の間ぐらいの中途半端なものになってしまっている気がします。

@Harutaka-Tsujino @yttmwork @ToshiyaMatsuoka @rikita-fujizono @shion-sagawa @Kinoshita-Tatsuya 
「ここはこうあるべきでは？」という意見を下さい。
方針さえ提示してもらえれば修正作業及び動作確認はやりますのでお気軽に！

2019-03-16 11:07 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +		BYTE m_blue  = 255;
構造体なのでpublicにしていたのだと思いますが、現状、これらに直接アクセスさせるつもりで作っていますか？

2019-03-16 11:07 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +		BYTE& operator[](COMPONENTS colorComponent)
戻り値として参照返しちゃって問題無いですか？
他の部分でもコピーを返していたり参照を返していたりがマチマチな気がします。

2019-03-16 11:11 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +		BYTE m_blue  = 255;
アクセスさせるつもりで作っていました

2019-03-16 11:14 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +		BYTE m_blue  = 255;
```
Color color;
color.m_alpha = 0x00;
```
みたいなことが可能ということですね？
うーん、 `operator[]` を用意したのならそちらに統一した方が良いように思うのですが …

2019-03-16 11:14 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +		BYTE& operator[](COMPONENTS colorComponent)
for文で回しながら代入する機会ができると思っているので参照にしています

2019-03-16 11:15 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +		BYTE& operator[](COMPONENTS colorComponent)
あ、そうか、参照にしておかないと代入ができないのか。
失礼しました。

2019-03-16 11:17 UTC, Harutaka-Tsujino commented on GameFramework/Color/Color.h
> +		BYTE m_blue  = 255;
そうですね`operator[ ]`があるならprivateにしてclassにしてもいいかもしれないですね

2019-03-16 11:18 UTC, taishi-matsumura commented on GameFramework/Color/Color.h
> +		BYTE m_blue  = 255;
僕はそう思います。
ここの判断についてはちょっと他の人の意見を待ちましょうか。